'''
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
	
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
'''
size=4000
pent = [int(n*(3*n-1)/2) for n in range(1, size) ]

#print(pent[1500], pent[1998])
import itertools
chunk = 1000
d={}
hopx=0
hopy=1*chunk
for i, x in enumerate(pent[hopx:hopx+chunk]):
	#print(i, x)
	for y in pent[hopy + i+1: hopy + i+chunk+1]:
		#print(x+y, y-x)
		if x+y in pent and y-x in pent:
			d[(x, y)] = x - y
			print('found')
			
print(len(d))

#u= [(x, y) for x, y in itertools.product(pent, pent) if x != y and x + y in pent and x - y in pent]

#print(u)
			
		